# Generated by Django 3.2.9 on 2023-09-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='CRUD.role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(max_length=50),
        ),
    ]
