# Generated by Django 4.1.7 on 2023-09-06 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("CRUD", "0002_app_remove_user_date_of_birth_employee_job_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={},
        ),
        migrations.CreateModel(
            name="ProfileModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Modification Date",
                    ),
                ),
                (
                    "modified_data",
                    models.JSONField(default=dict, verbose_name="Modified Data"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_modifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile modification",
                "verbose_name_plural": "profile modifications",
            },
        ),
    ]
