# Generated by Django 3.2.9 on 2023-09-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_alter_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clients',
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
