# Generated by Django 3.2.9 on 2023-09-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20230910_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='CRUD.Client'),
        ),
    ]
