# Generated by Django 4.1.7 on 2023-09-07 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("CRUD", "0005_client_profilemodification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodification",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_modifications_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="profilemodification",
            name="modified_data",
            field=models.JSONField(
                default=dict, null=True, verbose_name="Modified Data"
            ),
        ),
        migrations.AlterField(
            model_name="profilemodification",
            name="modified_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Modification Date",
            ),
        ),
    ]
