# Generated by Django 4.1.7 on 2023-09-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CRUD", "0006_profilemodification_modified_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodification",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_modifications_created",
                to="CRUD.role",
                verbose_name="Modified By",
            ),
        ),
    ]
