# Generated by Django 4.1.7 on 2023-09-08 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CRUD", "0008_employeeprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmployeeProfile",
            new_name="Profile",
        ),
    ]
